apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          env:
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: service-secrets
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_DB
              value: "database"
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
            - name: init-script-volume
              mountPath: /docker-entrypoint-initdb.d
      initContainers:
        - name: init-script-loader
          image: busybox
          command: ['sh', '-c', 'cp /config/init.sql /docker-entrypoint-initdb.d/init.sql']
          volumeMounts:
            - name: init-script-volume
              mountPath: /docker-entrypoint-initdb.d
            - name: config-volume
              mountPath: /config
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
        - name: init-script-volume
          emptyDir: {}
        - name: config-volume
          configMap:
            name: init-script
