name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Ejecuta la acción al hacer push en la rama `main`

  pull_request:
    branches:
      - main  # Ejecuta las acciones al abrir un Pull Request hacia la rama `main`

jobs:
  ci-cd:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      ### 1. Checkout del repositorio ###
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          # super-linter needs the full git history to get the
          # list of files that changed across commits
          fetch-depth: 0

      ### 2. Ejecutar Linter  ###
      - name: Run Linter
        uses: super-linter/super-linter@v6.6.0  
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DISABLE_ERRORS: true
          IGNORE_GENERATED_FILES: true
          IGNORE_GITIGNORED_FILES: true
          VALIDATE_ALL_CODEBASE: false

      # ### 3. Ejecutar Pruebas  ###
      # - name: Run Tests
      #   run: |
      #     npm ci
      #     npm test

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # ### 4. Crear la imagen Docker ###
      # - name: Build Docker Image
      #   run: |
      #     # docker build -t ghcr.io/victorc02/app:${{ github.sha }} .
      #     docker build -t ghcr.io/victorc02/app:${{ github.sha }} \ -f Practica_Kubernetes/app/Dockerfile Practica_Kubernetes/app

      ### 5. Login en el Container Registry ###
      - name: Login to GitHub
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}  # Configurar en GitHub Secrets
          password: ${{ secrets.GITHUB_TOKEN }}  # Configurar en GitHub Secrets

      - name: Build and Push
        uses: docker/build-push-action@v2
        with: 
          push: true
          context: ./app
          tags: |
            victorc02/app:latest

      ### 6. Push de la imagen al Container Registry ###
      - name: Push Docker Image
        run: |
          docker push ghcr.io/victorc02/app:latest

      ## 7. Despliegue ###
      - name: Introductions to Set-Up
        run: |
          echo("Go to "Practica_Kubernetes/Scripts")
          echo("Execute init.sh")
          echo("Execute minikube service ingress-nginx-controller -n ingress-nginx")
